name: hyper_cli
description: Console program to generate views and controllers with the statefulWidget template.
version: 1.0.2
homepage: https://github.com/denyocrworld/hyper_cli

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
